name: Docker Build and Push

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with: 
          username: gamanayr
          password: "#GaMa0230"

    - name: Build and Push PHP-Env image
      run: |
        docker build -t gamanayr/website_4th_sem_1-php-env -f Dockerfile.php-env .
        docker push gamanayr/php-env

    - name: Build and Push MySQL-DB image
      run: |
        docker build -t gamanayr/website_4th_sem_1-mysqlidb -f Dockerfile.mysqlidb .
        docker push gamanayr/mysqlidb

    - name: Build and Push PHPMyAdmin image
      run: |
        docker build -t gamanayr/website_4th_sem_1-phpmyadmin -f Dockerfile.phpmyadmin .
        docker push gamanayr/phpmyadmin
