name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: gamanayr
          password: "#GaMa0230"
      
      - name: Build Docker Image
        run: docker build -t devops .
        
      - name: Tag Docker Image
        run: docker tag devops:latest gamanayr/devops:latest
      
      - name: Push Docker Image
        run: docker push gamanayr/devops:latest

      - name: Run Docker Container
        run: docker run -d -p 80:80 gamanayr/devops:latest
