name: Publish Docker image

on:
  push:
    branches: ['master']

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up XAMPP
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://sourceforge.net/projects/xampp/files/XAMPP%20Linux/8.2.4/xampp-linux-x64-8.2.4-0-installer.run
          chmod +x xampp-linux-x64-8.2.4-0-installer.run
          ./xampp-linux-x64-8.2.4-0-installer.run
          ln -s /opt/lampp/lampp /usr/local/bin/lampp

      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          mv composer.phar /usr/local/bin/composer

      - name: Install PHP Dependencies
        run: composer install

      - name: Start XAMPP
        run: lampp start

      - name: Stop XAMPP
        run: lampp stop
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: gamanayr
          password: "#GaMa0230"
      
      - name: Build Docker Image
        run: docker build -t devops .
        
      - name: Tag Docker Image
        run: docker tag devops:latest gamanayr/devops:latest
      
      - name: Push Docker Image
        run: docker push gamanayr/devops:latest

      - name: Run Docker Container
        run: docker run -d -p 80:80 gamanayr/devops:latest
